name: GitHub Server JSDoc Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./Server/src
          output_dir: ./Documents/Dev/Server
          config_file: conf.json
          template: minami
          front_page: README.md
